### ISSUE TITLE
Supremium bow causes arrows to bounce of all targets

### ISSUE THREAD

**Issue by MoarCoffeeProfit** [BlakeBr0/MysticalAgriculture#623] opened 2023-08-18 09:29 UTC
**Describe the bug**
Upgrading bows from Imperium [tier 4] to Supremium [tier 5] makes all arrows bounce off the target instead of damaging whatever it is fired upon

**To Reproduce**

Upgrade a bow to tier 5, try to shoot something

**Expected behavior**
Arrows should not bounce off the target

**Screenshots / Scripts / Logs**
Tried to make a screenshot, but it's hard to see 
![Screenshot 2023-08-18 112636](https://github.com/BlakeBr0/MysticalAgriculture/assets/142582204/bab81ce0-2ec4-4d99-bb1d-4a942098eac2)
![Screenshot 2023-08-18 112629](https://github.com/BlakeBr0/MysticalAgriculture/assets/142582204/324515a4-ce3e-49b9-9259-89b71e0241bb)
![Screenshot 2023-08-18 112608](https://github.com/BlakeBr0/MysticalAgriculture/assets/142582204/04e13ace-6789-4cd3-9c49-e2a3a5eb0477)

**Versions (please complete the following information):**
 - Minecraft: 1.19.2
 - Forge: 43.2.14
 - Cucumber: ?
 - Mystical Agriculture: 6.0.10
 - Allthemods: 8 1.021b

**Comment by BlakeBr0** [comment] 2023-09-18 03:23
I wasn't able to reproduce this. Is this still an issue you're experiencing? Is this always reproducible with just Mystical Agriculture installed?

**Comment by MoarCoffeeProfit** [comment] 2023-09-18 05:27
Hello,

The issue is that's is enchanted with Mending. On reddit I found a thread,
quite recent, that supremium swords don't do any damage if the sword has
mending, that seemed to be the case for the bow as well. Took a new bow,
leveled it to supremium and enchanted afterwards and no issues.

Cheers

**Comment by MoarCoffeeProfit** [comment] 2023-09-18 05:29
Link:

https://reddit.com/r/allthemods/s/1VDDwP3xp5

Cheers,

**Comment by BlakeBr0** [comment] 2023-09-18 18:21
Seems to be a different enchant called 'Unusing' according to that post. Either way it doesn't seem to be an issue on my end so I'll close this.

**Closed as completed by BlakeBr0** 2023-09-18 18:21 UTC
Labels: Bug
