### ISSUE TITLE
[1.16.4] Accelerator blocks don't work if not directly below the farmland on which crops grow.

### ISSUE THREAD

**Issue by Ruchian** [BlakeBr0/MysticalAgriculture#384] opened 2021-01-03 01:07 UTC
In my findings I noticed the following at least:
Dirt will cause accelerator blocks not to function. If you wish to hide them a few layers lower (as the higher tier ones have a lot of range anyway and put a few machines in between or simply cables, you cannot. Placing dirt on top of the accelerator blocks will cause any farm land a few air blocks above that to not work. 
It might affect other opague blocks. 

To reproduce:
Make a nice tower of maybe 10 accelerator block. Place dirt on top, have some air between (2 blocks for walking space for example), place your farmland  in air above it.

Expected: 
Crops still grow quickly, like... nuts quickly. The range for Supremium tier is after all 60 blocks. The first crop is diffidently in range. 

No screenshots, hard to screenshot. xD

 - Minecraft: 1.16.4
 - Forge: 35.1.13
 - Cucumber: 4.1.5
 - Mystical Agriculture: 4.1.3

**Comment by BlakeBr0** [comment] 2021-02-14 06:12
I was not able to reproduce this with your instructions.

**Comment by BlakeBr0** [comment] 2021-03-24 18:11
I'm going to close this. If it's still an issue you can let me know.

**Closed as completed by BlakeBr0** 2021-03-24 18:11 UTC
Labels: Bug
