### ISSUE TITLE
[1.16.4] JEI recipes missing in multiplayer

### ISSUE THREAD

**Issue by stanedav** [BlakeBr0/MysticalAgriculture#387] opened 2021-02-12 15:07 UTC
JEI recipes are missing in multiplayer, unless a singleplayer world was openend before.

Versions:
Forge: 35.1.37
Cucumber-1.16.4-4.1.6.jar
jei-1.16.4-7.6.1.71.jar
MysticalAgriculture-1.16.4-4.1.4.jar

It seems that there is still error with recipes in JEI now showing in multiplayer over LAN.
Host is able to see the recipes (e.g. the seeds) but anybody who joined to game not.

**Comment by BlakeBr0** [comment] 2021-02-14 05:33
I didn't test this using the 'open to lan' button but with a regular server everything seems to work fine.

**Comment by Zaseru** [comment] 2021-02-19 20:22
im having issues as well. none of the seed or augment recipes show up in jei

**Comment by Sunekaer** [comment] 2021-02-24 15:29
Can confirm also having this issue in FTB Endeavour

**Comment by BlakeBr0** [comment] 2021-02-25 07:51
I can't reproduce this. Logs/reproduction steps would be helpful. Also are seed reprocessor recipes also missing?

**Comment by BlakeBr0** [comment] 2021-02-25 09:51
I just released version 4.1.8 of Cucumber Library which may fix this issue. Please let me know if it doesn't.

**Comment by Sunekaer** [comment] 2021-02-25 11:56
@BlakeBr0 
Will test and let you know, the way I can recreate it is by logging on to a server without going SP first.
It does only seem to be an issue on "modded" seeds, the vanilla like glowstone works fine, but any modded like silver, tin and so on doesn't.

![image](https://user-images.githubusercontent.com/18720460/109149785-54539500-7768-11eb-91fe-d1377ebf75a7.png)
![image](https://user-images.githubusercontent.com/18720460/109150180-cd52ec80-7768-11eb-9cac-0d2ec2fd4e7a.png)
![image](https://user-images.githubusercontent.com/18720460/109150144-bdd3a380-7768-11eb-9f9d-f642d31a3f21.png)

**Comment by BlakeBr0** [comment] 2021-02-26 01:44
That issue is a different issue that I'll be addressing later.

**Comment by BlakeBr0** [comment] 2021-03-17 18:18
I believe this is fixed with Cucumber version 4.1.8.

**Closed as completed by BlakeBr0** 2021-03-17 18:18 UTC
Labels: Bug, 1.16, Cucumber
